# ---- build stage ----
FROM node:20-alpine AS build
WORKDIR /app
COPY apps/web/package.json ./
COPY package-lock.json ./
RUN npm ci
COPY apps/web/ .
RUN npm config set cache /workspaces/likasun/.npm-cache && npm config set prefix /workspaces/likasun/.npm-global
RUN npm run build

# ---- runtime stage ----
FROM node:20-alpine AS runtime
RUN adduser -D -u 10002 raybeam
WORKDIR /app
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public
USER 10002
ENV NODE_ENV=production
CMD ["node", "server.js"]
