version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: ops/api.Dockerfile
    ports:
      - "8000:8000"
  web:
    build:
      context: ..
      dockerfile: ops/web.Dockerfile
    ports:
      - "3000:3000"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: raybeam
      POSTGRES_PASSWORD: raybeam
      POSTGRES_DB: raybeam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
