name: release
on:
  push:
    tags: ['v*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: docker build -f ops/Dockerfile.api -t ghcr.io/${{ github.repository }}/raybeam-api:${{ github.ref_name }} .

      - name: Build Web image
        run: docker build -f ops/Dockerfile.web -t ghcr.io/${{ github.repository }}/raybeam-web:${{ github.ref_name }} .

      - name: Push images (tag + latest)
        run: |
          for IMG in raybeam-api raybeam-web; do
            docker tag ghcr.io/${{ github.repository }}/$IMG:${{ github.ref_name }} ghcr.io/${{ github.repository }}/$IMG:latest
            docker push ghcr.io/${{ github.repository }}/$IMG:${{ github.ref_name }}
            docker push ghcr.io/${{ github.repository }}/$IMG:latest
          done

      - name: SBOM API
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}/raybeam-api:${{ github.ref_name }}
          output-file: sbom-api.spdx.json

      - name: SBOM Web
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}/raybeam-web:${{ github.ref_name }}
          output-file: sbom-web.spdx.json

      - name: Scan API Image
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/${{ github.repository }}/raybeam-api:${{ github.ref_name }}
          fail-build: false

      - name: Upload artifacts (v4)
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            sbom-api.spdx.json
            sbom-web.spdx.json

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            sbom-api.spdx.json
            sbom-web.spdx.json
