name: web-e2e
on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install deps
        working-directory: apps/web
        run: npm ci

      # Browsers are preinstalled in this image (no download)
      - name: Build & start app
        working-directory: apps/web
        run: |
          npm run build
          npm run start &

      - name: Run Playwright tests
        working-directory: apps/web
        env:
          # browsers already in image; no download step needed
          PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
        run: npm run test:ci
